In [1]:
import pandas as pd
import numpy as np
import re

# 2019

In [2]:
dataBooking2019 = pd.read_excel('D://Master/SSP/Projekat/data/raw/2019/Booking_2019.xlsx', index_col=0)

In [3]:
dataBooking2019.head()

Booked by    Guest Name(s)    Check-in   Check-out  \
Book Number                                                               
2.245705e+09  Veeravalli, Gopi  Gopi Veeravalli  2019-04-03  2019-04-06   
2.071623e+09    Kretov, Nikita    Nikita Kretov  2019-04-06  2019-04-11   
3.037388e+09      Yuheng Huang     Yuheng Huang  2019-04-07  2019-04-08   
3.181655e+09        LI, FENGJU        FENGJU LI  2019-04-10  2019-04-11   
3.642009e+09        LI, FENGJU              NaN  2019-04-11  2019-04-12   

                        Booked on Status  Rooms  People  Adults  Children  \
Book Number                                                                 
2.245705e+09  2019-03-30 19:53:46     ok      1       2     NaN       NaN   
2.071623e+09  2019-03-01 09:25:42     ok      1       2     NaN       NaN   
3.037388e+09  2019-03-31 07:50:45     ok      1       2     NaN       NaN   
3.181655e+09  2019-04-02 13:30:27     ok      1       2     NaN       NaN   
3.642009e+09  2019-04-02 15:03:10     ok      1       2     NaN       NaN   

             Children's age(s)    Price  Commission % Commission Amount  \
Book Number                                                               
2.245705e+09               NaN  117 EUR            18         21.06 EUR   
2.071623e+09               NaN  200 EUR            18            36 EUR   
3.037388e+09               NaN   39 EUR            18          7.02 EUR   
3.181655e+09               NaN   39 EUR            18          7.02 EUR   
3.642009e+09               NaN   40 EUR            18           7.2 EUR   

             Payment Status Payment Method Accommodation  Grade  
Book Number                                                      
2.245705e+09            NaN            NaN             A   10.0  
2.071623e+09            NaN            NaN             A    NaN  
3.037388e+09            NaN            NaN             C    NaN  
3.181655e+09            NaN            NaN             D    8.0  
3.642009e+09            NaN            NaN             C    8.0

In [4]:
dataBooking2019 = dataBooking2019.reset_index()

In [5]:
dataBooking2019['Book Number'].count()

222

In [6]:
dataBooking2019.drop_duplicates(subset=['Book Number'], keep='first', inplace=True)

In [7]:
#Adding advisor name
dataBooking2019['Advertiser'] = 'Booking'

In [8]:
#Editing names
print(dataBooking2019['Guest Name(s)'].isnull().unique())
print(dataBooking2019['Booked by'].isnull().unique())


[False  True]
[False  True]


In [9]:
dataBooking2019['Guest Name(s)'].fillna('', inplace=True)
dataBooking2019['Booked by'].fillna('', inplace=True)

In [10]:
dataBooking2019['Guest Name(s)'].unique()

array(['Gopi Veeravalli', 'Nikita Kretov', 'Yuheng Huang', 'FENGJU LI',
       '', 'Frederic Le Masson', 'Alok Prasad', 'Brad Foreman',
       'Mika Sainio', 'Fanhua Kong', 'Nanou Van Beveren',
       'Lars Balszuweit; Oliver Scheel', 'Mickaël Huneau',
       'Michele Burton', 'JOANNA KULSKA', 'Oana Atodiresei',
       'James Boustead', 'Laura Robertson', 'Iñigo Pinedo Guardamino',
       'myriam turquety', 'Mrdan Zivic', 'Agnieszka Mutwicka',
       'Arja Heinonen', 'Jan-Kees van Es', 'Rok Jelovčan',
       'Daniel Dworak', 'Tomasz Bedza', 'Vladimir Efimov',
       'Rene Belanger', 'Wendy Bentley', 'Alexandra Petit',
       'Sandie Lahaye', 'Debbie Henderson', 'Lucia Palmero',
       'JORIS GAONA', 'Ilnar Miftakhov', 'Thomas Lucas',
       'Maria Kudryavtseva', 'Joelle Dhondt', 'Lorna Verlinden',
       'Kate Englander', 'Nina Niskanen', 'alper öncüer',
       'Victoria Walkden', 'Roel Guntlisbergen', 'Anna Turunen',
       'Simon Holl', 'Roger Sutherland', 'Alexander Hilbring',
     

In [11]:
dataBooking2019['Booked by'].unique()

array(['Veeravalli, Gopi', 'Kretov, Nikita', 'Yuheng Huang', 'LI, FENGJU',
       'Le Masson, Frederic', 'Prasad, Alok', 'Foreman, Brad',
       'Sainio, Mika', 'Kong, Fanhua', 'Van Beveren, Nanou',
       'Scheel, Oliver', 'Huneau, Mickaël', 'Burton, Michele',
       'KULSKA, JOANNA', 'Atodiresei, Oana', 'Boustead, James',
       'Robertson, Laura', 'Pinedo Guardamino, Iñigo', 'turquety, myriam',
       'Zivic, Mrdan', 'Mutwicka, Agnieszka', 'Heinonen, Arja',
       'van Es, Jan-Kees', 'Jelovčan, Rok', 'Dworak, Daniel',
       'Bedza, Tomasz', 'Efimov, Vladimir', 'Belanger, Rene',
       'Bentley, Wendy', 'Petit, Alexandra', 'Lahaye, Sandie',
       'Henderson, Debbie', 'Palmero, Lucia', 'GAONA, JORIS',
       'Miftakhov, Ilnar', 'Lucas, Thomas', 'Kudryavtseva, Maria',
       'Dhondt, Joelle', 'Verlinden, Lorna', 'Englander, Kate',
       'Niskanen, Nina', 'öncüer, alper', 'Victoria Walkden',
       'Guntlisbergen, Roel', 'Turunen, Anna', 'Holl, Simon',
       'Sutherland, Roger', 'Hi

In [12]:
dataBooking2019['Guest Name(s)'] = dataBooking2019['Guest Name(s)'].str.title()
dataBooking2019['Booked by'] = dataBooking2019['Booked by'].str.title()

In [13]:
#Editing dates
#Dropping dates where check-in is after check-out and where booked on is after check-in
dataBooking2019 = dataBooking2019[dataBooking2019['Check-in'] < dataBooking2019['Check-out']]
dataBooking2019 = dataBooking2019[pd.to_datetime(dataBooking2019['Booked on']).dt.date <= pd.to_datetime(dataBooking2019['Check-in'])]
#Transforming dates in different format
dataBooking2019['Check-in'] = pd.to_datetime(dataBooking2019['Check-in']).dt.strftime('%d.%m.%Y')
dataBooking2019['Check-out'] = pd.to_datetime(dataBooking2019['Check-out']).dt.strftime('%d.%m.%Y')
dataBooking2019['Booked on'] = pd.to_datetime(dataBooking2019['Booked on']).dt.strftime('%d.%m.%Y')

In [14]:
dataBooking2019.head()

Book Number         Booked by    Guest Name(s)    Check-in   Check-out  \
0  2.245705e+09  Veeravalli, Gopi  Gopi Veeravalli  03.04.2019  06.04.2019   
1  2.071623e+09    Kretov, Nikita    Nikita Kretov  06.04.2019  11.04.2019   
2  3.037388e+09      Yuheng Huang     Yuheng Huang  07.04.2019  08.04.2019   
3  3.181655e+09        Li, Fengju        Fengju Li  10.04.2019  11.04.2019   
4  3.642009e+09        Li, Fengju                   11.04.2019  12.04.2019   

    Booked on Status  Rooms  People  Adults  Children Children's age(s)  \
0  30.03.2019     ok      1       2     NaN       NaN               NaN   
1  01.03.2019     ok      1       2     NaN       NaN               NaN   
2  31.03.2019     ok      1       2     NaN       NaN               NaN   
3  02.04.2019     ok      1       2     NaN       NaN               NaN   
4  02.04.2019     ok      1       2     NaN       NaN               NaN   

     Price  Commission % Commission Amount Payment Status Payment Method  \
0  117 EUR            18         21.06 EUR            NaN            NaN   
1  200 EUR            18            36 EUR            NaN            NaN   
2   39 EUR            18          7.02 EUR            NaN            NaN   
3   39 EUR            18          7.02 EUR            NaN            NaN   
4   40 EUR            18           7.2 EUR            NaN            NaN   

  Accommodation  Grade Advertiser  
0             A   10.0    Booking  
1             A    NaN    Booking  
2             C    NaN    Booking  
3             D    8.0    Booking  
4             C    8.0    Booking

In [15]:
#Renaming dates
dataBooking2019.rename(columns={'Check-in': 'Start Date', 'Check-out': 'End Date'}, inplace=True)

In [16]:
#Renaming status
dataBooking2019['Status'].unique()

array(['ok', 'cancelled'], dtype=object)

In [17]:
dataBooking2019['Status'] = dataBooking2019['Status'].replace({'ok': 'Confirmed'})
dataBooking2019['Status'] = dataBooking2019['Status'].replace({'cancelled': 'Cancelled'})

In [18]:
#Counting adults 
dataBooking2019['Children'].unique()

array([nan,  2.,  3.,  1.,  0.])

In [19]:
dataBooking2019['Children'].fillna(0, inplace=True)
dataBooking2019['Adults'] = dataBooking2019['People'] - dataBooking2019['Children']

In [20]:
#Cleaning EUR from commision amount and price
dataBooking2019['Commission Amount'] = dataBooking2019['Commission Amount'].str.replace('EUR', '')
dataBooking2019['Price'] = dataBooking2019['Price'].str.replace('EUR', '')

In [21]:
#Calculating commissiona amount without commission
dataBooking2019['Commission Amount'] = round(dataBooking2019['Price'].astype(float)*dataBooking2019['Commission %'].astype(int)/100, 2)
dataBooking2019['Price'] = round(dataBooking2019['Price'].astype(float) - dataBooking2019['Commission Amount'], 2)

In [22]:
#Renaming accomodation
mapping = {'A': 'One-Bedroom Apartment with Balcony and Sea View', 
           'B': 'Studio with Patio', 
           'C': 'Studio with Patio and Sea View',
           'D': 'One-Bedroom Apartment with Patio and Sea View'}

dataBooking2019['Accommodation'] = dataBooking2019['Accommodation'].replace(mapping)

In [23]:
dataBooking2019['Accommodation'].unique()

array(['One-Bedroom Apartment with Balcony and Sea View',
       'Studio with Patio and Sea View',
       'One-Bedroom Apartment with Patio and Sea View', 'D,A',
       'Studio with Patio', 'S'], dtype=object)

In [24]:
#Editing grade
dataBooking2019['Grade'].fillna(0, inplace=True)

In [25]:
#Dropping unvalid accommodations
valid_accommodations = ['One-Bedroom Apartment with Balcony and Sea View', 'Studio with Patio', 'Studio with Patio and Sea View', 'One-Bedroom Apartment with Patio and Sea View']
dataBooking2019 = dataBooking2019[dataBooking2019['Accommodation'].isin(valid_accommodations)]

In [26]:
#Calculating price in $ and RSD
# dataBooking2019['Price_$'] = round(dataBooking2019['Price'].astype(float)*1.09, 2)
# dataBooking2019['Price_RSD'] = round(dataBooking2019['Price'].astype(float)*117.23, 2)

In [27]:
#Renaming columns
dataBooking2019.rename(columns={'Guest Name(s)': 'Guest Name',  'People': 'NumberOfPeople', 'Adults': 'NumberOfAdults', 'Children': 'NumberOfChildren', "Children's age(s)": "Children's Age", 'Booked by' : 'Booked By', 'Booked on' : 'Booked On'}, inplace=True)

In [28]:
dataBooking2019.columns

Index(['Book Number', 'Booked By', 'Guest Name', 'Start Date', 'End Date',
       'Booked On', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's Age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

In [29]:
dataBooking2019["Children's Age"].unique()

array([nan, '5, 7', '5, 5', 6, 1, 2, '2, 4', '15, 6', '8, 15', '13, 9',
       '10, 5', '16, 17', '12, 12', '4, 1', '14, 10'], dtype=object)

In [30]:
dataBooking2019.columns

Index(['Book Number', 'Booked By', 'Guest Name', 'Start Date', 'End Date',
       'Booked On', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's Age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

# 2020

In [31]:
dataBooking2020 = pd.read_excel('D://Master/SSP/Projekat/data/raw/2020/Booking_2020.xlsx', index_col=0)

In [32]:
dataBooking2020.head()

Booked by          Guest Name(s)    Check-in  \
Book Number                                                                 
3044838719      Mária, Sárikné Deutsch  Sárikné Deutsch Mária  2020-07-10   
2210088623         Gniazdowska, Monika    Izabela Klimczewska  2020-07-15   
2310781853   Sárkány, Előd Szilveszter     Aleksandra Gęsicka  2020-07-16   
2274513344              GWIZDZ, ALICJA        Anna Przeworska  2020-07-23   
3612440501               Kolenda, Anna            Adam Filiks  2020-07-23   

              Check-out            Booked on Status  Rooms  People  Adults  \
Book Number                                                                  
3044838719   2020-07-15  2020-01-06 17:36:36     ok      1       2     NaN   
2210088623   2020-07-17  2020-07-14 21:17:35     ok      1       2     NaN   
2310781853   2020-07-18  2020-07-14 11:40:39     ok      1       2     NaN   
2274513344   2020-07-26  2020-07-21 21:23:02     ok      1       2     NaN   
3612440501   2020-07-26  2020-07-22 08:40:19     ok      1       2     NaN   

             Children Children's age(s)    Price  Commission %  \
Book Number                                                      
3044838719        NaN               NaN  360 EUR            18   
2210088623        NaN               NaN   78 EUR            18   
2310781853        NaN               NaN   58 EUR            18   
2274513344        NaN               NaN   87 EUR            18   
3612440501        NaN               NaN  117 EUR            18   

            Commission Amount Payment Status Payment Method Acommodation  \
Book Number                                                                
3044838719           64.8 EUR            NaN            NaN            C   
2210088623          14.04 EUR            NaN            NaN            C   
2310781853          10.44 EUR    Paid online   Virtual card            A   
2274513344          15.66 EUR    Paid online   Virtual card            A   
3612440501          21.06 EUR            NaN            NaN            D   

             Grade  
Book Number         
3044838719     9.0  
2210088623    10.0  
2310781853     7.0  
2274513344     NaN  
3612440501    10.0

In [33]:
def processingBooking(dataBooking):
    dataBooking['Advertiser'] = 'Booking'
    dataBooking['Guest Name(s)'].fillna('', inplace=True)
    dataBooking['Booked by'].fillna('', inplace=True)
    dataBooking['Guest Name(s)'] = dataBooking['Guest Name(s)'].str.title()
    dataBooking['Booked by'] = dataBooking['Booked by'].str.title()
    dataBooking = dataBooking[dataBooking['Check-in'] < dataBooking['Check-out']]
    dataBooking = dataBooking[pd.to_datetime(dataBooking['Booked on']).dt.date <= pd.to_datetime(dataBooking['Check-in'])]
    dataBooking['Check-in'] = pd.to_datetime(dataBooking['Check-in']).dt.strftime('%d.%m.%Y')
    dataBooking['Check-out'] = pd.to_datetime(dataBooking['Check-out']).dt.strftime('%d.%m.%Y')
    dataBooking['Booked on'] = pd.to_datetime(dataBooking['Booked on']).dt.strftime('%d.%m.%Y')
    dataBooking.rename(columns={'Check-in': 'Start date', 'Check-out': 'End date'}, inplace=True)
    
    dataBooking['Status'] = dataBooking['Status'].replace({'ok': 'Confirmed'})
    dataBooking['Status'] = dataBooking['Status'].replace({'OK': 'Confirmed'})
    dataBooking['Status'] = dataBooking['Status'].replace({'cancelled': 'Cancelled'})
    dataBooking['Status'] = dataBooking['Status'].replace({'canceled': 'Cancelled'})
    dataBooking['Children'].fillna(0, inplace=True)
    dataBooking['Adults'] = dataBooking['People'] - dataBooking['Children']
    dataBooking['Commission Amount'] = dataBooking['Commission Amount'].str.replace('EUR', '')
    dataBooking['Price'] = dataBooking['Price'].str.replace('EUR', '')
    dataBooking['Commission Amount'] = round(dataBooking['Price'].astype(float)*dataBooking['Commission %'].astype(int)/100, 2)
    dataBooking['Price'] = round(dataBooking['Price'].astype(float) - dataBooking['Commission Amount'], 2)
    
    mapping = {'A': 'One-Bedroom Apartment with Balcony and Sea View', 
           'B': 'Studio with Patio', 
           'C': 'Studio with Patio and Sea View',
           'D': 'One-Bedroom Apartment with Patio and Sea View'}
    
    dataBooking['Accommodation'] = dataBooking['Accommodation'].replace(mapping)

    dataBooking['Grade'].fillna(0, inplace=True)
    valid_accommodations = ['One-Bedroom Apartment with Balcony and Sea View', 'Studio with Patio', 'Studio with Patio and Sea View', 'One-Bedroom Apartment with Patio and Sea View']
    dataBooking = dataBooking[dataBooking['Accommodation'].isin(valid_accommodations)]
    
#     dataBooking['Price_$'] = round(dataBooking['Price'].astype(float)*1.09, 2)
#     dataBooking['Price_RSD'] = round(dataBooking['Price'].astype(float)*117.23, 2)
    dataBooking.rename(columns={'Guest Name(s)': 'Guest name',  'People': 'NumberOfPeople', 'Adults': 'NumberOfAdults', 'Children': 'NumberOfChildren', "Children's age(s)": "Children's age"}, inplace=True)
    return dataBooking

In [34]:
# Renaming column
dataBooking2020.rename(columns = {'Acommodation' : 'Accommodation'}, inplace = True)

In [35]:
dataBooking2020 = processingBooking(dataBooking2020)

In [36]:
dataBooking2020.head()

Booked by             Guest name  Start date  \
Book Number                                                                 
3044838719      Mária, Sárikné Deutsch  Sárikné Deutsch Mária  10.07.2020   
2210088623         Gniazdowska, Monika    Izabela Klimczewska  15.07.2020   
2310781853   Sárkány, Előd Szilveszter     Aleksandra Gęsicka  16.07.2020   
2274513344              Gwizdz, Alicja        Anna Przeworska  23.07.2020   
3612440501               Kolenda, Anna            Adam Filiks  23.07.2020   

               End date   Booked on     Status  Rooms  NumberOfPeople  \
Book Number                                                             
3044838719   15.07.2020  06.01.2020  Confirmed      1               2   
2210088623   17.07.2020  14.07.2020  Confirmed      1               2   
2310781853   18.07.2020  14.07.2020  Confirmed      1               2   
2274513344   26.07.2020  21.07.2020  Confirmed      1               2   
3612440501   26.07.2020  22.07.2020  Confirmed      1               2   

             NumberOfAdults  NumberOfChildren Children's age   Price  \
Book Number                                                            
3044838719              2.0               0.0            NaN  295.20   
2210088623              2.0               0.0            NaN   63.96   
2310781853              2.0               0.0            NaN   47.56   
2274513344              2.0               0.0            NaN   71.34   
3612440501              2.0               0.0            NaN   95.94   

             Commission %  Commission Amount Payment Status Payment Method  \
Book Number                                                                  
3044838719             18              64.80            NaN            NaN   
2210088623             18              14.04            NaN            NaN   
2310781853             18              10.44    Paid online   Virtual card   
2274513344             18              15.66    Paid online   Virtual card   
3612440501             18              21.06            NaN            NaN   

                                               Accommodation  Grade Advertiser  
Book Number                                                                     
3044838719                    Studio with Patio and Sea View    9.0    Booking  
2210088623                    Studio with Patio and Sea View   10.0    Booking  
2310781853   One-Bedroom Apartment with Balcony and Sea View    7.0    Booking  
2274513344   One-Bedroom Apartment with Balcony and Sea View    0.0    Booking  
3612440501     One-Bedroom Apartment with Patio and Sea View   10.0    Booking

In [37]:
dataBooking2020['Accommodation'].unique()

array(['Studio with Patio and Sea View',
       'One-Bedroom Apartment with Balcony and Sea View',
       'One-Bedroom Apartment with Patio and Sea View',
       'Studio with Patio'], dtype=object)

In [38]:
dataBooking2020.columns

Index(['Booked by', 'Guest name', 'Start date', 'End date', 'Booked on',
       'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

In [39]:
# Check if dataframes have the same column name
column_names_dataBooking2019 = set(dataBooking2019.columns)
column_names_dataBooking2020 = set(dataBooking2020.columns)

if column_names_dataBooking2019 == column_names_dataBooking2020:
    print("Both DataFrames have the same column names.")
else:
    print("Column names in the two DataFrames are not the same.")

Column names in the two DataFrames are not the same.


In [40]:
dataBooking2020['Status'].unique()

array(['Confirmed', 'Cancelled'], dtype=object)

In [41]:
dataBooking2020['Rooms'].unique()

array([1], dtype=int64)

In [42]:
dataBooking2020['NumberOfPeople'].unique()

array([2, 3, 1, 4], dtype=int64)

In [43]:
dataBooking2020['NumberOfAdults'].unique()

array([2., 3., 1., 4.])

In [44]:
dataBooking2020['NumberOfChildren'].unique()

array([0., 1., 2.])

In [45]:
dataBooking2020["Children's age"].unique()

array([nan, 17, 0, 1, '6, 3', 12], dtype=object)

In [46]:
dataBooking2020['Commission %'].unique()

array([18], dtype=int64)

In [47]:
dataBooking2020['Payment Status'].unique()

array([nan, 'Paid online'], dtype=object)

In [48]:
dataBooking2020['Payment Method'].unique()

array([nan, 'Virtual card'], dtype=object)

In [49]:
dataBooking2020['Grade'].unique()

array([ 9., 10.,  7.,  0.,  8.])

In [50]:
dataBooking2020 = dataBooking2020.reset_index()

In [51]:
dataBooking2020.head()

Book Number                  Booked by             Guest name  Start date  \
0   3044838719     Mária, Sárikné Deutsch  Sárikné Deutsch Mária  10.07.2020   
1   2210088623        Gniazdowska, Monika    Izabela Klimczewska  15.07.2020   
2   2310781853  Sárkány, Előd Szilveszter     Aleksandra Gęsicka  16.07.2020   
3   2274513344             Gwizdz, Alicja        Anna Przeworska  23.07.2020   
4   3612440501              Kolenda, Anna            Adam Filiks  23.07.2020   

     End date   Booked on     Status  Rooms  NumberOfPeople  NumberOfAdults  \
0  15.07.2020  06.01.2020  Confirmed      1               2             2.0   
1  17.07.2020  14.07.2020  Confirmed      1               2             2.0   
2  18.07.2020  14.07.2020  Confirmed      1               2             2.0   
3  26.07.2020  21.07.2020  Confirmed      1               2             2.0   
4  26.07.2020  22.07.2020  Confirmed      1               2             2.0   

   NumberOfChildren Children's age   Price  Commission %  Commission Amount  \
0               0.0            NaN  295.20            18              64.80   
1               0.0            NaN   63.96            18              14.04   
2               0.0            NaN   47.56            18              10.44   
3               0.0            NaN   71.34            18              15.66   
4               0.0            NaN   95.94            18              21.06   

  Payment Status Payment Method  \
0            NaN            NaN   
1            NaN            NaN   
2    Paid online   Virtual card   
3    Paid online   Virtual card   
4            NaN            NaN   

                                     Accommodation  Grade Advertiser  
0                   Studio with Patio and Sea View    9.0    Booking  
1                   Studio with Patio and Sea View   10.0    Booking  
2  One-Bedroom Apartment with Balcony and Sea View    7.0    Booking  
3  One-Bedroom Apartment with Balcony and Sea View    0.0    Booking  
4    One-Bedroom Apartment with Patio and Sea View   10.0    Booking

In [52]:
dataBooking2020.columns

Index(['Book Number', 'Booked by', 'Guest name', 'Start date', 'End date',
       'Booked on', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

In [53]:
dataBooking2020['Book Number'].unique()

array([3044838719, 2210088623, 2310781853, 2274513344, 3612440501,
       2224416656, 2284117766, 3666861902, 3168558138, 3335452243,
       3251250059, 2307791873, 3299147332, 2184010775, 2720125985,
       3020331127, 2198008434, 2844997397, 3594871097, 3431170671,
       3843171828, 2688496317, 3737705639, 2668756614, 3992438269,
       2227128291, 3662346745, 2864174409, 3217038516, 2642922280,
       2476055321, 2688128194, 3595829045], dtype=int64)

In [54]:
dataBooking2020['Book Number'].count()

34

In [55]:
if dataBooking2020['Book Number'].nunique() == len(dataBooking2020['Book Number']):
    print(f"All non-missing values in the column '{'Book Number'}' are unique.")
else:
    print(f"Not all non-missing values in the column '{'Book Number'}' are unique.")

Not all non-missing values in the column 'Book Number' are unique.


In [56]:
duplicates = dataBooking2020[dataBooking2020['Book Number'].duplicated(keep=False)]
print(duplicates)

    Book Number           Booked by         Guest name  Start date  \
24   3992438269  Balakhonkin, Anton  Anton Balakhonkin  31.08.2020   
25   3992438269  Balakhonkin, Anton  Anton Balakhonkin  31.08.2020   

      End date   Booked on     Status  Rooms  NumberOfPeople  NumberOfAdults  \
24  11.09.2020  06.01.2020  Confirmed      1               4             4.0   
25  11.09.2020  06.01.2020  Confirmed      1               2             1.0   

    NumberOfChildren Children's age   Price  Commission %  Commission Amount  \
24               0.0              0  699.46            18             153.54   
25               1.0              1  396.06            18              86.94   

   Payment Status Payment Method  \
24            NaN            NaN   
25            NaN            NaN   

                                      Accommodation  Grade Advertiser  
24  One-Bedroom Apartment with Balcony and Sea View   10.0    Booking  
25                                Studio with Patio   

In [57]:
dataBooking2020.drop_duplicates(subset=['Book Number'], keep='first', inplace=True)

In [58]:
dataBooking2020['Book Number'].count()

33

In [59]:
dataBooking2020.head()

Book Number                  Booked by             Guest name  Start date  \
0   3044838719     Mária, Sárikné Deutsch  Sárikné Deutsch Mária  10.07.2020   
1   2210088623        Gniazdowska, Monika    Izabela Klimczewska  15.07.2020   
2   2310781853  Sárkány, Előd Szilveszter     Aleksandra Gęsicka  16.07.2020   
3   2274513344             Gwizdz, Alicja        Anna Przeworska  23.07.2020   
4   3612440501              Kolenda, Anna            Adam Filiks  23.07.2020   

     End date   Booked on     Status  Rooms  NumberOfPeople  NumberOfAdults  \
0  15.07.2020  06.01.2020  Confirmed      1               2             2.0   
1  17.07.2020  14.07.2020  Confirmed      1               2             2.0   
2  18.07.2020  14.07.2020  Confirmed      1               2             2.0   
3  26.07.2020  21.07.2020  Confirmed      1               2             2.0   
4  26.07.2020  22.07.2020  Confirmed      1               2             2.0   

   NumberOfChildren Children's age   Price  Commission %  Commission Amount  \
0               0.0            NaN  295.20            18              64.80   
1               0.0            NaN   63.96            18              14.04   
2               0.0            NaN   47.56            18              10.44   
3               0.0            NaN   71.34            18              15.66   
4               0.0            NaN   95.94            18              21.06   

  Payment Status Payment Method  \
0            NaN            NaN   
1            NaN            NaN   
2    Paid online   Virtual card   
3    Paid online   Virtual card   
4            NaN            NaN   

                                     Accommodation  Grade Advertiser  
0                   Studio with Patio and Sea View    9.0    Booking  
1                   Studio with Patio and Sea View   10.0    Booking  
2  One-Bedroom Apartment with Balcony and Sea View    7.0    Booking  
3  One-Bedroom Apartment with Balcony and Sea View    0.0    Booking  
4    One-Bedroom Apartment with Patio and Sea View   10.0    Booking

In [60]:
dataBooking2020["Children's age"].unique()

array([nan, 17, 0, '6, 3', 12], dtype=object)

In [61]:
dataBooking2020.columns

Index(['Book Number', 'Booked by', 'Guest name', 'Start date', 'End date',
       'Booked on', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

In [62]:
dataBooking2020.rename(columns = {'Booked by' : 'Booked By', 
                                  'Guest name' : 'Guest Name', 
                                  'Start date' : 'Start Date', 
                                  'End date' : 'End Date',
                                  'Booked on' : 'Booked On', 
                                  "Children's age" : "Children's Age"}, inplace = True)

# 2021

In [63]:
dataBooking2021 = pd.read_excel('D://Master/SSP/Projekat/data/raw/2021/Booking_2021.xlsx', index_col=0)

In [64]:
for i in range (0, 74):
    print('i: ',i)
    print(dataBooking2021['occypancy'][i])
    print(dataBooking2021['number_of_guests'][i])

i:  0
2 guests
2.0
i:  1
2 guests
2.0
i:  2
4 adults
4.0
i:  3
4 adults
4.0
i:  4
4 adults
4.0
i:  5
3 adults
3.0
i:  6
2 guests
2.0
i:  7
2 guests
2.0
i:  8
2 adults
2.0
i:  9
2 guests
2.0
i:  10
2 guests
2.0
i:  11
2 guests
2.0
i:  12
4 adults
4.0
i:  13
2 guests
2.0
i:  14
2 guests
2.0
i:  15
2 guests
2.0
i:  16
2 guests
2.0
i:  17
2 guests
2.0
i:  18
2 guests
2.0
i:  19
2 guests
2.0
i:  20
2 guests
2.0
i:  21
2 adults, 1 child (0) 
2.0
i:  22
1 guest
1.0
i:  23
2 guests
2.0
i:  24
2 guests
2.0
i:  25
2 guests
2.0
i:  26
2 guests
2.0
i:  27
2 guests
2.0
i:  28
2 adults, 1 child (0) 
2.0
i:  29
2 guests
2.0
i:  30
2 guests
2.0
i:  31
1 guest
1.0
i:  32
2 guests
2.0
i:  33
2 guests
2.0
i:  34
2 guests
2.0
i:  35
2 guests
2.0
i:  36
4 guests
4.0
i:  37
2 guests
2.0
i:  38
nan
nan
i:  39
1 guest
1.0
i:  40
3 guests
3.0
i:  41
2 guests
2.0
i:  42
2 guests
2.0
i:  43
2 guests
2.0
i:  44
2 guests
2.0
i:  45
2 guests
2.0
i:  46
2 guests
2.0
i:  47
2 guests
2.0
i:  48
2 guests
2.0
i:  49
2 g

In [65]:
dataBooking2021.head()

arrival_date departure_date  \
guest                                            
Richard Young        2021-07-13     2021-07-18   
Eileen Quinn         2021-09-18     2021-09-21   
Horváth Zsuzsanna    2021-07-26     2021-08-02   
Sirok Gábor          2021-07-16     2021-07-30   
Serg Kostrukov       2021-06-28     2021-06-30   

                                                               room  \
guest                                                                 
Richard Young                        Studio with Patio and Sea View   
Eileen Quinn        One-Bedroom Apartment with Balcony and Sea View   
Horváth Zsuzsanna     One-Bedroom Apartment with Patio and Sea View   
Sirok Gábor         One-Bedroom Apartment with Balcony and Sea View   
Serg Kostrukov      One-Bedroom Apartment with Balcony and Sea View   

                   booking_date status   price  commision    booking_id  \
guest                                                                     
Richard Young        2020-01-07     OK   310.0      55.80  2.177211e+09   
Eileen Quinn         2020-01-09     OK   186.0      33.48  3.595829e+09   
Horváth Zsuzsanna    2021-05-06     OK   518.0      93.24  2.184747e+09   
Sirok Gábor          2021-05-07     OK  1016.0     182.88  3.216186e+09   
Serg Kostrukov       2021-05-14     OK   108.0      19.44  2.149859e+09   

                   occypancy  number_of_guests  
guest                                           
Richard Young       2 guests               2.0  
Eileen Quinn        2 guests               2.0  
Horváth Zsuzsanna   4 adults               4.0  
Sirok Gábor         4 adults               4.0  
Serg Kostrukov      4 adults               4.0

In [66]:
dataBooking2021 = dataBooking2021.reset_index()

In [67]:
dataBooking2020.columns

Index(['Book Number', 'Booked By', 'Guest Name', 'Start Date', 'End Date',
       'Booked On', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's Age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser'],
      dtype='object')

In [68]:
dataBooking2021['occypancy'].unique()

array(['2 guests', '4 adults', '3 adults', '2 adults',
       '2 adults, 1 child (0) ', '1 guest', '4 guests', nan, '3 guests',
       '2 adults, 2 children (2,11) ', '6 guests'], dtype=object)

In [69]:
dataBooking2021['occypancy'].fillna(0, inplace=True)

In [70]:
subsequence = ' child'
dataBooking2021['NumberOfChildren'] = dataBooking2021['occypancy'].str.extract(f'(.){subsequence}').fillna(0)

In [71]:
dataBooking2021['NumberOfChildren'].unique()

array([0, '1', '2'], dtype=object)

In [72]:
dataBooking2021['number_of_guests'].unique()

array([ 2.,  4.,  3.,  1., nan,  6.])

In [73]:
dataBooking2021['number_of_guests'].fillna(0, inplace = True)

In [74]:
dataBooking2021['NumberOfChildren'].unique()

array([0, '1', '2'], dtype=object)

In [75]:
dataBooking2021["Children's age"] = dataBooking2021['occypancy'].str.extract(r'\((.*?)\)')

In [76]:
dataBooking2021["Children's age"].unique()

array([nan, '0', '2,11'], dtype=object)

In [77]:
dataBooking2021["Children's age"].fillna(0, inplace = True)

In [78]:
dataBooking2021.drop('occypancy', axis=1, inplace=True)

In [79]:
dataBooking2021['status'].unique()

array(['OK', 'Risk-Free', nan], dtype=object)

In [80]:
dataBooking2021['commision'].unique()

array([ 55.8 ,  33.48,  93.24, 182.88,  19.44,  89.64,  31.68,  15.84,
       194.4 ,  55.44,  32.76,  61.74,  13.32,  31.86,  17.64,  66.24,
        23.76,  74.34,   8.82,   7.92,  39.96,   7.02,  46.08,  18.9 ,
        79.38,  14.04,  21.24,  35.1 ,   9.72,  10.62,  95.58,    nan,
        23.04,   0.  ,  34.56,  21.06,  26.64,  57.6 ,  11.52,  62.1 ,
        70.56,  54.54,  69.84,  29.88,  70.2 ,  38.88])

In [81]:
dataBooking2021['commision'].fillna(0, inplace=True)

In [82]:
if dataBooking2021['booking_id'].nunique() == len(dataBooking2021['booking_id']):
    print(f"All non-missing values in the column '{'booking_id'}' are unique.")
else:
    print(f"Not all non-missing values in the column '{'booking_id'}' are unique.")

Not all non-missing values in the column 'booking_id' are unique.


In [83]:
dataBooking2021.drop_duplicates(subset=['booking_id'], keep='first', inplace=True)

In [84]:
dataBooking2021['booking_id'].unique()

array([2.17721115e+09, 3.59582904e+09, 2.18474703e+09, 3.21618597e+09,
       2.14985881e+09, 2.80110159e+09, 2.99363468e+09, 2.84619000e+09,
       2.35929346e+09, 2.62276186e+09, 2.62273989e+09, 2.41119312e+09,
       2.49352966e+09, 3.87879513e+09, 2.72187942e+09, 2.43618069e+09,
       2.25840982e+09, 3.05055503e+09, 2.32660242e+09, 3.46033594e+09,
       2.74500796e+09, 3.40135891e+09, 3.03562287e+09, 2.95544372e+09,
       2.76728039e+09, 2.76720344e+09, 3.00256418e+09, 3.09020599e+09,
       2.29423057e+09, 2.14907878e+09, 2.29420305e+09, 3.03355854e+09,
       2.33002090e+09, 3.03518611e+09, 2.67693333e+09, 2.67693541e+09,
       3.10725829e+09, 2.20265491e+09,            nan, 2.67496252e+09,
       3.71753327e+09, 2.53487650e+09, 2.50742292e+09, 3.12499508e+09,
       2.28122715e+09, 2.56533142e+09, 2.79315968e+09, 3.45956849e+09,
       2.87472504e+09, 3.62166293e+09, 2.74881830e+09, 3.44338210e+09,
       3.49559974e+09, 3.67667972e+09, 2.18529150e+09, 3.52679094e+09,
      

In [85]:
dataBooking2021.dropna(subset=['booking_id'], inplace=True)

In [86]:
def processingBooking2021(dataBooking):
    dataBooking.rename(columns={'guest': 'Guest Name', 
                                'arrival_date': 'Check-in', 
                                'departure_date': 'Check-out', 
                                'room' : 'Accommodation',
                                'booking_date' : 'Booked On',
                                'status' : 'Status',
                                'price' : 'Price', 
                                'commision' : 'Commission Amount',
                                'booking_id' : 'Book Number',
                                'occypancy' : 'Occupancy',
                                'number_of_guests' : 'NumberOfAdults',}, inplace=True)
    
    dataBooking['NumberOfChildren'] = dataBooking['NumberOfChildren'].astype(int)
    dataBooking['NumberOfAdults'] = dataBooking['NumberOfAdults'].astype(int)
    dataBooking['NumberOfPeople'] = dataBooking['NumberOfAdults'] + dataBooking['NumberOfChildren']
    
    
    dataBooking['Advertiser'] = 'Booking'
    dataBooking['Guest Name'].fillna('', inplace=True)
    dataBooking['Guest Name'] = dataBooking['Guest Name'].str.title()
    dataBooking = dataBooking[dataBooking['Check-in'] < dataBooking['Check-out']]
    dataBooking = dataBooking[pd.to_datetime(dataBooking['Booked On']).dt.date <= pd.to_datetime(dataBooking['Check-in'])]
    dataBooking['Check-in'] = pd.to_datetime(dataBooking['Check-in']).dt.strftime('%d.%m.%Y')
    dataBooking['Check-out'] = pd.to_datetime(dataBooking['Check-out']).dt.strftime('%d.%m.%Y')
    dataBooking['Booked On'] = pd.to_datetime(dataBooking['Booked On']).dt.strftime('%d.%m.%Y')
    dataBooking.rename(columns={'Check-in': 'Start date', 'Check-out': 'End date'}, inplace=True)
    
    dataBooking['Status'] = dataBooking['Status'].replace({'Risk-Free': 'Arriving'})
    dataBooking['Status'] = dataBooking['Status'].replace({'OK': 'Confirmed'})
    dataBooking['Status'] = dataBooking['Status'].replace({'Smart Flex': 'Arriving'})
    dataBooking['Price'] = dataBooking['Price'].astype(str).map(lambda x: re.sub(r'€ ', '', x))
    dataBooking['Price'] = round(dataBooking['Price'].astype(float) - dataBooking['Commission Amount'].astype(float), 2)
    dataBooking['Commission Amount'] = dataBooking['Commission Amount'].astype(str).map(lambda x: re.sub(r'€ ', '', x))
    
    mapping = {'A': 'One-Bedroom Apartment with Balcony and Sea View', 
           'B': 'Studio with Patio', 
           'C': 'Studio with Patio and Sea View',
           'D': 'One-Bedroom Apartment with Patio and Sea View'}
    
    dataBooking['Accommodation'] = dataBooking['Accommodation'].replace(mapping)

    valid_accommodations = ['One-Bedroom Apartment with Balcony and Sea View', 'Studio with Patio', 'Studio with Patio and Sea View', 'One-Bedroom Apartment with Patio and Sea View']
    dataBooking = dataBooking[dataBooking['Accommodation'].isin(valid_accommodations)]
    
#     dataBooking['Price_$'] = round(dataBooking['Price'].astype(float)*1.09, 2)
#     dataBooking['Price_RSD'] = round(dataBooking['Price'].astype(float)*117.23, 2)
#     dataBooking.rename(columns={'Price': 'Price_€'}, inplace=True)
    return dataBooking

In [87]:
dataBooking2021 = processingBooking2021(dataBooking2021)

In [88]:
dataBooking2021.head()

Guest Name  Start date    End date  \
0      Richard Young   13.07.2021  18.07.2021   
1       Eileen Quinn   18.09.2021  21.09.2021   
2  Horváth Zsuzsanna   26.07.2021  02.08.2021   
3        Sirok Gábor   16.07.2021  30.07.2021   
4     Serg Kostrukov   28.06.2021  30.06.2021   

                                     Accommodation   Booked On     Status  \
0                   Studio with Patio and Sea View  07.01.2020  Confirmed   
1  One-Bedroom Apartment with Balcony and Sea View  09.01.2020  Confirmed   
2    One-Bedroom Apartment with Patio and Sea View  06.05.2021  Confirmed   
3  One-Bedroom Apartment with Balcony and Sea View  07.05.2021  Confirmed   
4  One-Bedroom Apartment with Balcony and Sea View  14.05.2021  Confirmed   

    Price Commission Amount   Book Number  NumberOfAdults  NumberOfChildren  \
0  254.20              55.8  2.177211e+09               2                 0   
1  152.52             33.48  3.595829e+09               2                 0   
2  424.76             93.24  2.184747e+09               4                 0   
3  833.12            182.88  3.216186e+09               4                 0   
4   88.56             19.44  2.149859e+09               4                 0   

  Children's age  NumberOfPeople Advertiser  
0              0               2    Booking  
1              0               2    Booking  
2              0               4    Booking  
3              0               4    Booking  
4              0               4    Booking

In [89]:
dataBooking2021['Accommodation'].unique()

array(['Studio with Patio and Sea View',
       'One-Bedroom Apartment with Balcony and Sea View',
       'One-Bedroom Apartment with Patio and Sea View',
       'Studio with Patio'], dtype=object)

In [90]:
dataBooking2021.columns

Index(['Guest Name', 'Start date', 'End date', 'Accommodation', 'Booked On',
       'Status', 'Price', 'Commission Amount', 'Book Number', 'NumberOfAdults',
       'NumberOfChildren', 'Children's age', 'NumberOfPeople', 'Advertiser'],
      dtype='object')

In [91]:
dataBooking2021.rename(columns={'Start date': 'Start Date', 
                                'End date': 'End Date', 
                                "Children's age": "Children's Age"}, inplace=True)

# 2022

In [92]:
dataBooking2022= pd.read_excel('D://Master/SSP/Projekat/data/raw/2022/Booking_2022.xlsx', index_col=0)

In [93]:
dataBooking2022.head()

arrival_date departure_date  \
guest                                        
Richard Young    2022-07-13     2022-07-20   
Eileen Quinn     2022-09-17     2022-09-20   
Phillip Ball     2022-05-19     2022-05-21   
Cleo Rotunno     2022-06-17     2022-06-20   
Emily Brown      2022-06-02     2022-06-05   

                                                           room booking_date  \
guest                                                                          
Richard Young                    Studio with Patio and Sea View   2020-01-07   
Eileen Quinn    One-Bedroom Apartment with Balcony and Sea View   2020-01-09   
Phillip Ball      One-Bedroom Apartment with Patio and Sea View   2022-02-17   
Cleo Rotunno    One-Bedroom Apartment with Balcony and Sea View   2022-03-03   
Emily Brown     One-Bedroom Apartment with Balcony and Sea View   2022-03-14   

               status  price  commision  booking_id occypancy  \
guest                                                           
Richard Young      OK    434      78.12  2177211152  2 guests   
Eileen Quinn       OK    186      33.48  3595829045  2 guests   
Phillip Ball       OK     98      17.64  2906488360  2 guests   
Cleo Rotunno       OK    162      29.16  3777625256  2 guests   
Emily Brown        OK    162      29.16  2936175841  2 guests   

                number_of_guests  grade  
guest                                    
Richard Young                  2    NaN  
Eileen Quinn                   2    NaN  
Phillip Ball                   2    8.0  
Cleo Rotunno                   2   10.0  
Emily Brown                    2    NaN

In [94]:
for i in range (0, 71):
    print('i: ',i)
    print(dataBooking2022['occypancy'][i])
    print(dataBooking2022['number_of_guests'][i])

i:  0
2 guests
2
i:  1
2 guests
2
i:  2
2 guests
2
i:  3
2 guests
2
i:  4
2 guests
2
i:  5
2 guests
2
i:  6
2 guests
2
i:  7
2 guests
2
i:  8
2 guests
2
i:  9
2 guests
2
i:  10
2 adults
2
i:  11
2 guests
2
i:  12
2 guests
2
i:  13
2 guests
2
i:  14
2 guests
2
i:  15
2 guests
2
i:  16
2 guests
2
i:  17
2 guests
2
i:  18
2 guests
2
i:  19
1 guest
1
i:  20
2 guests
2
i:  21
2 guests
2
i:  22
2 guests
2
i:  23
1 guest
1
i:  24
2 guests
2
i:  25
2 guests
2
i:  26
2 guests
2
i:  27
2 guests
2
i:  28
2 guests
2
i:  29
2 guests
2
i:  30
2 guests
2
i:  31
2 guests
2
i:  32
2 guests
2
i:  33
2 guests
2
i:  34
2 guests
2
i:  35
2 guests
2
i:  36
2 guests
2
i:  37
3 guests
3
i:  38
2 guests
2
i:  39
2 guests
2
i:  40
2 guests
2
i:  41
2 guests
2
i:  42
2 guests
2
i:  43
2 guests
2
i:  44
2 guests
2
i:  45
2 guests
2
i:  46
2 guests
2
i:  47
2 guests
2
i:  48
2 guests
2
i:  49
2 guests
2
i:  50
2 guests
2
i:  51
2 guests
2
i:  52
1 adult, 1 child (0) 
1
i:  53
2 guests
2
i:  54
2 guests
2
i:  55
2 

In [95]:
dataBooking2022 = dataBooking2022.reset_index()

In [96]:
dataBooking2022.head()

guest arrival_date departure_date  \
0  Richard Young    2022-07-13     2022-07-20   
1   Eileen Quinn    2022-09-17     2022-09-20   
2   Phillip Ball    2022-05-19     2022-05-21   
3   Cleo Rotunno    2022-06-17     2022-06-20   
4    Emily Brown    2022-06-02     2022-06-05   

                                              room booking_date status  price  \
0                   Studio with Patio and Sea View   2020-01-07     OK    434   
1  One-Bedroom Apartment with Balcony and Sea View   2020-01-09     OK    186   
2    One-Bedroom Apartment with Patio and Sea View   2022-02-17     OK     98   
3  One-Bedroom Apartment with Balcony and Sea View   2022-03-03     OK    162   
4  One-Bedroom Apartment with Balcony and Sea View   2022-03-14     OK    162   

   commision  booking_id occypancy  number_of_guests  grade  
0      78.12  2177211152  2 guests                 2    NaN  
1      33.48  3595829045  2 guests                 2    NaN  
2      17.64  2906488360  2 guests                 2    8.0  
3      29.16  3777625256  2 guests                 2   10.0  
4      29.16  2936175841  2 guests                 2    NaN

In [97]:
dataBooking2022.columns

Index(['guest', 'arrival_date', 'departure_date', 'room', 'booking_date',
       'status', 'price', 'commision', 'booking_id', 'occypancy',
       'number_of_guests', 'grade'],
      dtype='object')

In [98]:
dataBooking2022['occypancy'].unique()

array(['2 guests', '2 adults', '1 guest', '3 guests',
       '1 adult, 1 child (0) '], dtype=object)

In [99]:
subsequence = ' child'
dataBooking2022['NumberOfChildren'] = dataBooking2022['occypancy'].str.extract(f'(.){subsequence}').fillna(0)

In [100]:
dataBooking2021['NumberOfChildren'].unique()

array([0, 1, 2])

In [101]:
dataBooking2022['number_of_guests'].unique()

array([2, 1, 3], dtype=int64)

In [102]:
dataBooking2022['NumberOfChildren'].unique()

array([0, '1'], dtype=object)

In [103]:
dataBooking2022["Children's age"] = dataBooking2022['occypancy'].str.extract(r'\((.*?)\)')

In [104]:
dataBooking2022["Children's age"].unique()

array([nan, '0'], dtype=object)

In [105]:
dataBooking2022["Children's age"].fillna(0, inplace = True)

In [106]:
dataBooking2022.drop('occypancy', axis=1, inplace=True)

In [107]:
dataBooking2022['status'].unique()

array(['OK', 'Cancelled', 'Smart Flex'], dtype=object)

In [108]:
dataBooking2022['commision'].unique()

array([ 78.12,  33.48,  17.64,  29.16,  35.28,  49.68,   7.92,   8.82,
       171.18,  82.44,  29.7 ,  80.64,  42.12,  16.2 ,  95.58,   7.2 ,
        19.8 ,  33.3 ,  45.  ,  63.  ,  39.6 ,  15.84,  32.4 ,  49.5 ,
        38.88,  14.4 ,  31.68,  79.2 ,  40.5 ,  50.4 ,  19.44,  25.2 ,
        32.58,  14.04,  24.3 ,  21.06,  11.7 ,  36.  ,  48.6 ,  21.6 ])

In [109]:
if dataBooking2022['booking_id'].nunique() == len(dataBooking2022['booking_id']):
    print(f"All non-missing values in the column '{'booking_id'}' are unique.")
else:
    print(f"Not all non-missing values in the column '{'booking_id'}' are unique.")

Not all non-missing values in the column 'booking_id' are unique.


In [110]:
dataBooking2022.drop_duplicates(subset=['booking_id'], keep='first', inplace=True)

In [111]:
dataBooking2022['booking_id'].unique()

array([2177211152, 3595829045, 2906488360, 3777625256, 2936175841,
       3212883028, 3108247316, 3532151522, 3696490722, 3527181508,
       2799254617, 2892041330, 3744652502, 3744634074, 3133609348,
       2359400878, 3969827568, 2735070211, 3140759524, 2920961987,
       3780221223, 3749194759, 3952797885, 3820166423, 2270670894,
       3326224982, 2754622468, 3467223567, 3086929427, 2199306885,
       2915283772, 2197349114, 2600268751, 2896899770, 2256619892,
       3506978869, 3637195891, 2746955968, 3847268467, 3815278809,
       3834641870, 2931585589, 2128831651, 3894131761, 3705895403,
       3678162739, 3669552047, 2765990756, 2626987354, 3010493932,
       3494875475, 2884003258, 3488069170, 2369504400, 2686459322,
       2144458575, 3249462422, 3527613470, 2703656690, 3087068843,
       2175910000, 3970623369, 3441599315, 2897130215, 2918383892,
       3410174307, 3965650875, 3473824160, 2187141203, 2446909164],
      dtype=int64)

In [112]:
dataBooking2022.head()

guest arrival_date departure_date  \
0  Richard Young    2022-07-13     2022-07-20   
1   Eileen Quinn    2022-09-17     2022-09-20   
2   Phillip Ball    2022-05-19     2022-05-21   
3   Cleo Rotunno    2022-06-17     2022-06-20   
4    Emily Brown    2022-06-02     2022-06-05   

                                              room booking_date status  price  \
0                   Studio with Patio and Sea View   2020-01-07     OK    434   
1  One-Bedroom Apartment with Balcony and Sea View   2020-01-09     OK    186   
2    One-Bedroom Apartment with Patio and Sea View   2022-02-17     OK     98   
3  One-Bedroom Apartment with Balcony and Sea View   2022-03-03     OK    162   
4  One-Bedroom Apartment with Balcony and Sea View   2022-03-14     OK    162   

   commision  booking_id  number_of_guests  grade NumberOfChildren  \
0      78.12  2177211152                 2    NaN                0   
1      33.48  3595829045                 2    NaN                0   
2      17.64  2906488360                 2    8.0                0   
3      29.16  3777625256                 2   10.0                0   
4      29.16  2936175841                 2    NaN                0   

  Children's age  
0              0  
1              0  
2              0  
3              0  
4              0

In [113]:
dataBooking2022 = processingBooking2021(dataBooking2022)

In [114]:
dataBooking2022.head()

Guest Name  Start date    End date  \
0  Richard Young   13.07.2022  20.07.2022   
1   Eileen Quinn   17.09.2022  20.09.2022   
2   Phillip Ball   19.05.2022  21.05.2022   
3   Cleo Rotunno   17.06.2022  20.06.2022   
4    Emily Brown   02.06.2022  05.06.2022   

                                     Accommodation   Booked On     Status  \
0                   Studio with Patio and Sea View  07.01.2020  Confirmed   
1  One-Bedroom Apartment with Balcony and Sea View  09.01.2020  Confirmed   
2    One-Bedroom Apartment with Patio and Sea View  17.02.2022  Confirmed   
3  One-Bedroom Apartment with Balcony and Sea View  03.03.2022  Confirmed   
4  One-Bedroom Apartment with Balcony and Sea View  14.03.2022  Confirmed   

    Price Commission Amount  Book Number  NumberOfAdults  grade  \
0  355.88             78.12   2177211152               2    NaN   
1  152.52             33.48   3595829045               2    NaN   
2   80.36             17.64   2906488360               2    8.0   
3  132.84             29.16   3777625256               2   10.0   
4  132.84             29.16   2936175841               2    NaN   

   NumberOfChildren Children's age  NumberOfPeople Advertiser  
0                 0              0               2    Booking  
1                 0              0               2    Booking  
2                 0              0               2    Booking  
3                 0              0               2    Booking  
4                 0              0               2    Booking

In [115]:
dataBooking2022['Accommodation'].unique()

array(['Studio with Patio and Sea View',
       'One-Bedroom Apartment with Balcony and Sea View',
       'One-Bedroom Apartment with Patio and Sea View',
       'Studio with Patio'], dtype=object)

In [116]:
dataBooking2022['grade'].unique()

array([nan,  8., 10.,  7.,  9.])

In [117]:
dataBooking2022['grade'].fillna(0, inplace = True)

In [118]:
dataBooking2022.rename(columns={'grade' : 'Grade'}, inplace = True)

In [119]:
dataBooking2022['Status'].unique()

array(['Confirmed', 'Cancelled', 'Arriving'], dtype=object)

In [120]:
dataBooking2022["Children's age"].unique()

array([0, '0'], dtype=object)

In [121]:
dataBooking2022["NumberOfChildren"].unique()

array([0, 1])

In [122]:
dataBooking2022.columns

Index(['Guest Name', 'Start date', 'End date', 'Accommodation', 'Booked On',
       'Status', 'Price', 'Commission Amount', 'Book Number', 'NumberOfAdults',
       'Grade', 'NumberOfChildren', 'Children's age', 'NumberOfPeople',
       'Advertiser'],
      dtype='object')

In [123]:
dataBooking2022.rename(columns={'Start date': 'Start Date', 
                                'End date': 'End Date',
                                "Children's age": "Children's Age"}, inplace=True)

# 2023

In [124]:
dataBooking2023= pd.read_excel('D://Master/SSP/Projekat/data/raw/2023/2023_booking.xlsx', index_col=0)

In [125]:
dataBooking2023.head()

Booked by     Guest Name(s)    Check-in   Check-out  \
Book Number                                                                
2374616608    De La Rosa, Juan   Juan De La Rosa  2023-04-17  2023-04-20   
2251062736   Cook, Christopher  Christopher Cook  2023-04-17  2023-04-21   
2337695567       cocco, silvia      silvia cocco  2023-04-17  2023-04-19   
3022962893        Abdin, Aytaj      Kamal Omarov  2023-04-18  2023-04-22   
3726049369       MORRIS, CRAIG      CRAIG MORRIS  2023-04-20  2023-04-22   

                       Booked on              Status  People  Adults  \
Book Number                                                            
2374616608   2023-01-03 18:42:14  cancelled_by_guest       2     NaN   
2251062736   2023-02-21 22:16:32                  ok       2     NaN   
2337695567   2023-03-18 12:08:35                  ok       2     NaN   
3022962893   2023-02-17 21:32:16                  ok       2     NaN   
3726049369   2023-02-26 10:18:19                  ok       2     NaN   

             Children Children's age(s)  ... Payment Method  \
Book Number                              ...                  
2374616608        NaN               NaN  ...            NaN   
2251062736        NaN               NaN  ...            NaN   
2337695567        NaN               NaN  ...            NaN   
3022962893        NaN               NaN  ...   Virtual card   
3726049369        NaN               NaN  ...            NaN   

                       Contact Staff Facilities Cleanliness Comfort  \
Book Number                                                           
2374616608     +27 83 226 9181   NaN        NaN         NaN     NaN   
2251062736     +49 170 5236337  10.0       10.0        10.0    10.0   
2337695567     +31 31625642536   9.0        9.0        10.0     9.0   
3022962893   +33 6 43 39 11 81   8.0        8.0         NaN     8.0   
3726049369     +91 99563 58674   NaN        NaN         NaN     NaN   

             Value for money  Location  Free WiFi  Total  
Book Number                                               
2374616608               NaN       NaN        NaN    NaN  
2251062736              10.0      10.0       10.0   10.0  
2337695567               9.0       9.0        9.0    9.0  
3022962893               8.0       8.0        8.0    8.0  
3726049369               NaN       NaN        NaN   10.0  

[5 rows x 24 columns]

In [126]:
dataBooking2023.columns

Index(['Booked by', 'Guest Name(s)', 'Check-in', 'Check-out', 'Booked on',
       'Status', 'People', 'Adults', 'Children', 'Children's age(s)', 'Price',
       'Commission %', 'Room', 'Payment Status', 'Payment Method', 'Contact',
       'Staff', 'Facilities', 'Cleanliness', 'Comfort', 'Value for money',
       'Location', 'Free WiFi', 'Total'],
      dtype='object')

In [127]:
dataBooking2023 = dataBooking2023.reset_index()

In [128]:
dataBooking2023.head()

Book Number          Booked by     Guest Name(s)    Check-in   Check-out  \
0   2374616608   De La Rosa, Juan   Juan De La Rosa  2023-04-17  2023-04-20   
1   2251062736  Cook, Christopher  Christopher Cook  2023-04-17  2023-04-21   
2   2337695567      cocco, silvia      silvia cocco  2023-04-17  2023-04-19   
3   3022962893       Abdin, Aytaj      Kamal Omarov  2023-04-18  2023-04-22   
4   3726049369      MORRIS, CRAIG      CRAIG MORRIS  2023-04-20  2023-04-22   

             Booked on              Status  People  Adults  Children  ...  \
0  2023-01-03 18:42:14  cancelled_by_guest       2     NaN       NaN  ...   
1  2023-02-21 22:16:32                  ok       2     NaN       NaN  ...   
2  2023-03-18 12:08:35                  ok       2     NaN       NaN  ...   
3  2023-02-17 21:32:16                  ok       2     NaN       NaN  ...   
4  2023-02-26 10:18:19                  ok       2     NaN       NaN  ...   

  Payment Method            Contact  Staff Facilities Cleanliness Comfort  \
0            NaN    +27 83 226 9181    NaN        NaN         NaN     NaN   
1            NaN    +49 170 5236337   10.0       10.0        10.0    10.0   
2            NaN    +31 31625642536    9.0        9.0        10.0     9.0   
3   Virtual card  +33 6 43 39 11 81    8.0        8.0         NaN     8.0   
4            NaN    +91 99563 58674    NaN        NaN         NaN     NaN   

  Value for money  Location  Free WiFi  Total  
0             NaN       NaN        NaN    NaN  
1            10.0      10.0       10.0   10.0  
2             9.0       9.0        9.0    9.0  
3             8.0       8.0        8.0    8.0  
4             NaN       NaN        NaN   10.0  

[5 rows x 25 columns]

In [129]:
if dataBooking2023['Book Number'].nunique() == len(dataBooking2023['Book Number']):
    print(f"All non-missing values in the column '{'Book Number'}' are unique.")
else:
    print(f"Not all non-missing values in the column '{'Book Number'}' are unique.")

All non-missing values in the column 'Book Number' are unique.


In [130]:
dataBooking2023['Status'].unique()

array(['cancelled_by_guest', 'ok', 'no_show'], dtype=object)

In [131]:
dataBooking2023['People'].unique()

array([2, 4, 1, 3], dtype=int64)

In [132]:
dataBooking2023['Adults'].unique()

array([nan,  2.,  1.])

In [133]:
dataBooking2023['Children'].unique()

array([nan,  2.,  1.,  3.])

In [134]:
dataBooking2023["Children's age(s)"].unique()

array([nan, '5,3', 1, 3, 4, '2,6', '4,5', 9, 0, '5,10', '7,2,2', '0,2'],
      dtype=object)

In [135]:
dataBooking2023['Price'].unique()

array(['150 EUR', '244 EUR', '104 EUR', '122 EUR', '177 EUR', '156 EUR',
       '195 EUR', '223 EUR', '402 EUR', '201 EUR', '165 EUR', '171 EUR',
       '134 EUR', '114 EUR', '224 EUR', '268 EUR', '285 EUR', '130 EUR',
       '469 EUR', '419 EUR', '205 EUR', '215 EUR', '144 EUR', '231 EUR',
       '154 EUR', '228 EUR', '330 EUR', '528 EUR', '385 EUR', '124 EUR',
       '300 EUR', '220 EUR', '128 EUR', '110 EUR', '328 EUR', '256 EUR',
       '198 EUR', '308 EUR', '72 EUR', '132 EUR', '525 EUR', '82 EUR',
       '216 EUR', '261 EUR', '248 EUR', '180 EUR', '425 EUR', '609 EUR',
       '360 EUR', '310 EUR', '348 EUR', '186 EUR', '595 EUR', '91 EUR',
       '368 EUR', '210 EUR', '270 EUR', '92 EUR', '97 EUR', '480 EUR',
       '183 EUR', '288 EUR', '434 EUR', '522 EUR', '240 EUR', '435 EUR',
       '1190 EUR', '490 EUR', '172.33 EUR', '280 EUR', '589 EUR',
       '181 EUR', '539 EUR', '67 EUR', '495 EUR', '399 EUR', '462 EUR',
       '499 EUR', '119 EUR', '520 EUR', '264 EUR'], dtype=object

In [136]:
dataBooking2023['Commission %'].unique()

array([18], dtype=int64)

In [137]:
dataBooking2023['Room'].unique()

array(['C - Studio with Patio and Sea View',
       'D - One-Bedroom Apartment with Patio and Sea View',
       'A - One-Bedroom Apartment with Balcony and Sea View',
       'B - Studio with Patio'], dtype=object)

In [138]:
dataBooking2023['Contact'].unique()

array(['+27 83 226 9181', '+49 170 5236337', '+31 31625642536',
       '+33 6 43 39 11 81', '+91 99563 58674', '+49 1577 2018127',
       '+44 7931 806900', '+90 544 270 86 82', '+44 7445 054462',
       '+358 50 3834653', '+33 6 19 84 55 20', '+44 7563 612108',
       '+33 6 79 38 52 84', '+389 78 409 794', '+49 1511 4141596',
       '+90 551 589 10 32', '+33 6 84 27 85 92', '+44 7585 227036',
       '+49 176 32316351', '+44 7850 093592', '+33 6 38 51 92 40',
       '+31 6 43643456', '+34 685 78 75 24', '+44 7772 189814',
       '+49 1578 9134181', '+45 51 88 03 34', '+33 6 67 69 23 84',
       '+33 6 71 87 34 09', '+44 7846 642165', '+33 6 80 04 89 27',
       '+31 6 48576518', nan, '+1 901-267-6089', '+31 6 30585740',
       '+44 7397 299786', '+65 8322 4546', '+33 6 30 69 74 95',
       '+45 28 12 00 74', '+33 6 15 14 30 23', '+33 6 43 07 72 59',
       '+61 450 059 972', '+33 6 25 40 95 86', '+374 94 987265',
       '+36 20 226 0548', '+49 173 2422152', '+90 530 906 39 56',
      

In [139]:
dataBooking2023['Staff'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [140]:
dataBooking2023['Facilities'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [141]:
dataBooking2023['Cleanliness'].unique()

array([nan, 10.,  6.,  9.,  8.])

In [142]:
dataBooking2023['Comfort'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [143]:
dataBooking2023['Value for money'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [144]:
dataBooking2023['Location'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [145]:
dataBooking2023['Free WiFi'].unique()

array([nan, 10.,  9.,  8.,  7.])

In [146]:
dataBooking2023['Total'].unique()

array([nan, 10.,  9.,  8.,  6.,  7.])

In [147]:
def processingBooking2023(dataBooking):
    dataBooking['Advertiser'] = 'Booking'
    
    dataBooking['Booked by'].fillna('', inplace=True)
    dataBooking['Booked by'] = dataBooking['Booked by'].str.title()
        
    dataBooking['Guest Name(s)'].fillna('', inplace=True)
    dataBooking['Guest Name(s)'] = dataBooking['Guest Name(s)'].str.title()
    
    
    dataBooking = dataBooking[dataBooking['Check-in'] < dataBooking['Check-out']]
    dataBooking = dataBooking[pd.to_datetime(dataBooking['Booked on']).dt.date <= pd.to_datetime(dataBooking['Check-in'])]
    dataBooking['Check-in'] = pd.to_datetime(dataBooking['Check-in']).dt.strftime('%d.%m.%Y')
    dataBooking['Check-out'] = pd.to_datetime(dataBooking['Check-out']).dt.strftime('%d.%m.%Y')
    dataBooking['Booked on'] = pd.to_datetime(dataBooking['Booked on']).dt.strftime('%d.%m.%Y')
    dataBooking.rename(columns={'Check-in': 'Start date', 'Check-out': 'End date'}, inplace=True)
    
    dataBooking['Status'] = dataBooking['Status'].replace({'ok': 'Confirmed'})
    dataBooking['Status'] = dataBooking['Status'].replace({'cancelled_by_guest': 'Cancelled'})
    dataBooking['Status'] = dataBooking['Status'].replace({'no_show': 'NoShow'})
    
    
    dataBooking['Children'].fillna(0, inplace=True)
    dataBooking['Adults'].fillna(0, inplace=True)
    dataBooking['Adults'] = dataBooking['People'] - dataBooking['Children']
    
    dataBooking["Children's age(s)"].fillna(0, inplace=True)
    
    dataBooking['Price'] = dataBooking['Price'].str.replace('EUR', '')
    dataBooking['Commission Amount'] = round(dataBooking['Price'].astype(float)*dataBooking['Commission %'].astype(int)/100, 2)
    dataBooking['Price'] = round(dataBooking['Price'].astype(float) - dataBooking['Commission Amount'], 2)
    
    dataBooking['Accommodation'] = dataBooking['Room'].str[4:]
    dataBooking.drop('Room', axis=1, inplace=True)
    
    dataBooking['Staff'].fillna(0, inplace=True)
    dataBooking['Facilities'].fillna(0, inplace=True)
    dataBooking['Cleanliness'].fillna(0, inplace=True)
    dataBooking['Comfort'].fillna(0, inplace=True)
    dataBooking['Value for money'].fillna(0, inplace=True)
    dataBooking['Location'].fillna(0, inplace=True)
    dataBooking['Free WiFi'].fillna(0, inplace=True)
    dataBooking['Total'].fillna(0, inplace=True)

    valid_accommodations = ['One-Bedroom Apartment with Balcony and Sea View', 'Studio with Patio', 'Studio with Patio and Sea View', 'One-Bedroom Apartment with Patio and Sea View']
    dataBooking = dataBooking[dataBooking['Accommodation'].isin(valid_accommodations)]
    
#     dataBooking['Price_$'] = round(dataBooking['Price'].astype(float)*1.09, 2)
#     dataBooking['Price_RSD'] = round(dataBooking['Price'].astype(float)*117.23, 2)
    dataBooking.rename(columns={'Guest Name(s)': 'Guest Name', 
                                'People': 'NumberOfPeople', 
                                'Adults': 'NumberOfAdults', 
                                'Children': 'NumberOfChildren', 
                                "Children's age(s)": "Children's Age",
                                'Check-in' : 'Start Date',
                                'Check-out': 'End Date',
                                'Booked by': 'Booked By',
                                'Booked on': 'Booked On',
                                'Value for money': 'Value For Money',
                                'Total': 'Grade'}, inplace=True)
    return dataBooking

In [148]:
dataBooking2023.columns

Index(['Book Number', 'Booked by', 'Guest Name(s)', 'Check-in', 'Check-out',
       'Booked on', 'Status', 'People', 'Adults', 'Children',
       'Children's age(s)', 'Price', 'Commission %', 'Room', 'Payment Status',
       'Payment Method', 'Contact', 'Staff', 'Facilities', 'Cleanliness',
       'Comfort', 'Value for money', 'Location', 'Free WiFi', 'Total'],
      dtype='object')

In [149]:
dataBooking2023 = processingBooking2023(dataBooking2023)

In [150]:
dataBooking2023.rename(columns={'Start date': 'Start Date', 'End date': 'End Date', }, inplace=True)

In [151]:
dataBooking2023.head()

Book Number          Booked By        Guest Name  Start Date    End Date  \
0   2374616608   De La Rosa, Juan   Juan De La Rosa  17.04.2023  20.04.2023   
1   2251062736  Cook, Christopher  Christopher Cook  17.04.2023  21.04.2023   
2   2337695567      Cocco, Silvia      Silvia Cocco  17.04.2023  19.04.2023   
3   3022962893       Abdin, Aytaj      Kamal Omarov  18.04.2023  22.04.2023   
4   3726049369      Morris, Craig      Craig Morris  20.04.2023  22.04.2023   

    Booked On     Status  NumberOfPeople  NumberOfAdults  NumberOfChildren  \
0  03.01.2023  Cancelled               2             2.0               0.0   
1  21.02.2023  Confirmed               2             2.0               0.0   
2  18.03.2023  Confirmed               2             2.0               0.0   
3  17.02.2023  Confirmed               2             2.0               0.0   
4  26.02.2023  Confirmed               2             2.0               0.0   

   ... Facilities  Cleanliness  Comfort Value For Money Location Free WiFi  \
0  ...        0.0          0.0      0.0             0.0      0.0       0.0   
1  ...       10.0         10.0     10.0            10.0     10.0      10.0   
2  ...        9.0         10.0      9.0             9.0      9.0       9.0   
3  ...        8.0          0.0      8.0             8.0      8.0       8.0   
4  ...        0.0          0.0      0.0             0.0      0.0       0.0   

   Grade  Advertiser  Commission Amount  \
0    0.0     Booking              27.00   
1   10.0     Booking              43.92   
2    9.0     Booking              18.72   
3    8.0     Booking              43.92   
4   10.0     Booking              18.72   

                                     Accommodation  
0                   Studio with Patio and Sea View  
1    One-Bedroom Apartment with Patio and Sea View  
2                   Studio with Patio and Sea View  
3  One-Bedroom Apartment with Balcony and Sea View  
4                   Studio with Patio and Sea View  

[5 rows x 27 columns]

# Merging

In [152]:
# Check if dataframes have the same column name
column_names_dataBooking2019 = set(dataBooking2019.columns)
column_names_dataBooking2020 = set(dataBooking2020.columns)

if column_names_dataBooking2019 == column_names_dataBooking2020:
    print("Both DataFrames have the same column names.")
else:
    print("Column names in the two DataFrames are not the same.")

Both DataFrames have the same column names.


In [153]:
# Check if dataframes have the same column name
column_names_dataBooking2019 = set(dataBooking2019.columns)
column_names_dataBooking2021 = set(dataBooking2021.columns)
# column_names_dataBooking2022 = set(dataBooking2022.columns)
# column_names_dataBooking2023 = set(dataBooking2023.columns)

if column_names_dataBooking2019 == column_names_dataBooking2021:
    print("Both DataFrames have the same column names.")
else:
    print("Column names in the two DataFrames are not the same.")

Column names in the two DataFrames are not the same.


In [154]:
not_common_columns = set(dataBooking2019.columns).symmetric_difference(set(dataBooking2021.columns))

print("Columns not common:", not_common_columns)


Columns not common: {'Booked By', 'Payment Method', 'Rooms', 'Grade', 'Commission %', 'Payment Status'}


In [155]:
merged1920 = pd.concat([dataBooking2019, dataBooking2020], ignore_index=True)

In [156]:
dataBooking2019.shape

(221, 20)

In [157]:
dataBooking2020.shape

(33, 20)

In [158]:
dataBooking2021.shape

(71, 14)

In [159]:
dataBooking2022.shape

(70, 15)

In [160]:
dataBooking2023.shape

(166, 27)

In [161]:
merged1920.shape

(254, 20)

In [162]:
mergedBooking = pd.concat([dataBooking2019, dataBooking2020, dataBooking2021, dataBooking2022, dataBooking2023], ignore_index=True)

In [163]:
mergedBooking.shape

(561, 28)

In [164]:
mergedBooking.head()

Book Number         Booked By       Guest Name  Start Date    End Date  \
0  2.245705e+09  Veeravalli, Gopi  Gopi Veeravalli  03.04.2019  06.04.2019   
1  2.071623e+09    Kretov, Nikita    Nikita Kretov  06.04.2019  11.04.2019   
2  3.037388e+09      Yuheng Huang     Yuheng Huang  07.04.2019  08.04.2019   
3  3.181655e+09        Li, Fengju        Fengju Li  10.04.2019  11.04.2019   
4  3.642009e+09        Li, Fengju                   11.04.2019  12.04.2019   

    Booked On     Status  Rooms  NumberOfPeople  NumberOfAdults  ...  Grade  \
0  30.03.2019  Confirmed    1.0               2             2.0  ...   10.0   
1  01.03.2019  Confirmed    1.0               2             2.0  ...    0.0   
2  31.03.2019  Confirmed    1.0               2             2.0  ...    0.0   
3  02.04.2019  Confirmed    1.0               2             2.0  ...    8.0   
4  02.04.2019  Confirmed    1.0               2             2.0  ...    8.0   

  Advertiser  Contact  Staff Facilities Cleanliness Comfort Value For Money  \
0    Booking      NaN    NaN        NaN         NaN     NaN             NaN   
1    Booking      NaN    NaN        NaN         NaN     NaN             NaN   
2    Booking      NaN    NaN        NaN         NaN     NaN             NaN   
3    Booking      NaN    NaN        NaN         NaN     NaN             NaN   
4    Booking      NaN    NaN        NaN         NaN     NaN             NaN   

   Location Free WiFi  
0       NaN       NaN  
1       NaN       NaN  
2       NaN       NaN  
3       NaN       NaN  
4       NaN       NaN  

[5 rows x 28 columns]

In [165]:
mergedBooking.columns

Index(['Book Number', 'Booked By', 'Guest Name', 'Start Date', 'End Date',
       'Booked On', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's Age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser', 'Contact', 'Staff',
       'Facilities', 'Cleanliness', 'Comfort', 'Value For Money', 'Location',
       'Free WiFi'],
      dtype='object')

In [166]:
mergedBooking.drop_duplicates(subset=['Book Number'], keep='first', inplace=True)

In [167]:
mergedBooking['Rooms'].unique()

array([ 1., nan])

In [168]:
mergedBooking['Payment Method'] = mergedBooking['Payment Method'].replace({'Virtual card': 'Card'})

In [169]:
mapping = {'One-Bedroom Apartment with Balcony and Sea View' : 'A',
           'Studio with Patio' : 'B',
           'Studio with Patio and Sea View' : 'C',
           'One-Bedroom Apartment with Patio and Sea View' : 'D'}

mergedBooking['Accommodation Type'] = mergedBooking['Accommodation'].replace(mapping)

In [170]:
mergedBooking.columns

Index(['Book Number', 'Booked By', 'Guest Name', 'Start Date', 'End Date',
       'Booked On', 'Status', 'Rooms', 'NumberOfPeople', 'NumberOfAdults',
       'NumberOfChildren', 'Children's Age', 'Price', 'Commission %',
       'Commission Amount', 'Payment Status', 'Payment Method',
       'Accommodation', 'Grade', 'Advertiser', 'Contact', 'Staff',
       'Facilities', 'Cleanliness', 'Comfort', 'Value For Money', 'Location',
       'Free WiFi', 'Accommodation Type'],
      dtype='object')

In [171]:
mergedBooking.shape

(558, 29)

In [172]:
mergedBooking.head()

Book Number         Booked By       Guest Name  Start Date    End Date  \
0  2.245705e+09  Veeravalli, Gopi  Gopi Veeravalli  03.04.2019  06.04.2019   
1  2.071623e+09    Kretov, Nikita    Nikita Kretov  06.04.2019  11.04.2019   
2  3.037388e+09      Yuheng Huang     Yuheng Huang  07.04.2019  08.04.2019   
3  3.181655e+09        Li, Fengju        Fengju Li  10.04.2019  11.04.2019   
4  3.642009e+09        Li, Fengju                   11.04.2019  12.04.2019   

    Booked On     Status  Rooms  NumberOfPeople  NumberOfAdults  ...  \
0  30.03.2019  Confirmed    1.0               2             2.0  ...   
1  01.03.2019  Confirmed    1.0               2             2.0  ...   
2  31.03.2019  Confirmed    1.0               2             2.0  ...   
3  02.04.2019  Confirmed    1.0               2             2.0  ...   
4  02.04.2019  Confirmed    1.0               2             2.0  ...   

   Advertiser Contact  Staff  Facilities Cleanliness Comfort Value For Money  \
0     Booking     NaN    NaN         NaN         NaN     NaN             NaN   
1     Booking     NaN    NaN         NaN         NaN     NaN             NaN   
2     Booking     NaN    NaN         NaN         NaN     NaN             NaN   
3     Booking     NaN    NaN         NaN         NaN     NaN             NaN   
4     Booking     NaN    NaN         NaN         NaN     NaN             NaN   

  Location  Free WiFi Accommodation Type  
0      NaN        NaN                  A  
1      NaN        NaN                  A  
2      NaN        NaN                  C  
3      NaN        NaN                  D  
4      NaN        NaN                  C  

[5 rows x 29 columns]

In [173]:
mergedBooking.rename(columns={'NumberOfPeople': 'Number Of People',
                            'NumberOfAdults': 'Number Of Adults',
                            'NumberOfChildren': 'Number Of Children',
                            'Commission %': 'Commission Percentage',
                            'NumberOfAdults': 'Number Of Adults',
                            'Price': 'Price_EUR',
                           }, inplace=True)

In [174]:
mergedBooking['Booked By'] = mergedBooking['Booked By'].str.replace(',', '')

In [175]:
mergedBooking["Children's Age"] = mergedBooking["Children's Age"].str.replace(',', ';')

In [177]:
mergedBooking = mergedBooking[mergedBooking['Price_EUR'] >= 0]

In [ ]:
# mergedBooking.to_csv('C://Users/k/Desktop/files/file/MergedBooking.csv', index_label='Id')

In [180]:
# upis u fajl
# mergedBooking.to_csv('D://Master/SSP/Projekat/data/processed/ProcessedBooking.csv', index=False)